<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEwsE6l1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEwsE6l1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEwsE6l1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEwsE6l1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEwsE6l1\App_KernelDevDebugContainer([
    'container.build_hash' => 'EwsE6l1',
    'container.build_id' => '3ad85f94',
    'container.build_time' => 1730220673,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEwsE6l1');
